# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Alpha\PycharmProjects\SimpleShutdownTimer\src\main\python\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from ui import mainwindow_rc



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(265, 99)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setIconSize(QtCore.QSize(228, 261))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxHours = QtWidgets.QSpinBox(self.frame)
        self.spinBoxHours.setObjectName("spinBoxHours")
        self.horizontalLayout.addWidget(self.spinBoxHours)
        self.spinBoxMinutes = QtWidgets.QSpinBox(self.frame)
        self.spinBoxMinutes.setMaximum(59)
        self.spinBoxMinutes.setObjectName("spinBoxMinutes")
        self.horizontalLayout.addWidget(self.spinBoxMinutes)
        self.spinBoxSeconds = QtWidgets.QSpinBox(self.frame)
        self.spinBoxSeconds.setMaximum(59)
        self.spinBoxSeconds.setObjectName("spinBoxSeconds")
        self.horizontalLayout.addWidget(self.spinBoxSeconds)
        self.verticalLayout.addWidget(self.frame)
        self.pushButtonOk = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.verticalLayout.addWidget(self.pushButtonOk)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 265, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setGeometry(QtCore.QRect(269, 125, 166, 94))
        self.menuMenu.setObjectName("menuMenu")
        self.menuLanguage = QtWidgets.QMenu(self.menuMenu)
        self.menuLanguage.setObjectName("menuLanguage")
        MainWindow.setMenuBar(self.menubar)
        self.actionCancel_shutdown = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCancel_shutdown.setIcon(icon1)
        self.actionCancel_shutdown.setObjectName("actionCancel_shutdown")
        self.actionEspa_ol = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/spanish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEspa_ol.setIcon(icon2)
        self.actionEspa_ol.setObjectName("actionEspa_ol")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/english.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnglish.setIcon(icon3)
        self.actionEnglish.setObjectName("actionEnglish")
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionEspa_ol)
        self.menuMenu.addAction(self.actionCancel_shutdown)
        self.menuMenu.addAction(self.menuLanguage.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ShutdownTimer"))
        self.label.setText(_translate("MainWindow", "Timer:"))
        self.spinBoxHours.setSuffix(_translate("MainWindow", " h"))
        self.spinBoxMinutes.setSuffix(_translate("MainWindow", " min"))
        self.spinBoxSeconds.setSuffix(_translate("MainWindow", " s"))
        self.pushButtonOk.setText(_translate("MainWindow", "Schedule"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.actionCancel_shutdown.setText(_translate("MainWindow", "Cancel shutdown"))
        self.actionEspa_ol.setText(_translate("MainWindow", "Español"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
